### ISSUE TITLE
Doesn't work on Firefox 62 for Linux

### ISSUE THREAD

**Issue by starkgate** [lllyasviel/MangaCraft#3]
After processing the image, MangaCraft opens a blank tab (about:blank), and doesn't give me the option to see the result. Attached the picture I tried it with.

![zodd](https://user-images.githubusercontent.com/12874678/45916937-6bdb1500-be6e-11e8-9fff-a963f14d068e.jpg)

**Comment by lllyasviel** [comment]
Is it OK with chrome?

**Comment by starkgate** [comment]
Just tried it out, it does work. Also tried firefox on Windows, doesn't work.

Some other suggestions :
- The percentages are a bit funky, sometimes they reset or go backwards 😄 
- I tried to upload a 7 MB scan (18 megapixels), got an error (firefox and chrome)
- The scans I uploaded don't look the same in mangacraft and in a regular image viewer
![i_view64_2018-09-22_14-58-29](https://user-images.githubusercontent.com/12874678/45917464-08ee7b80-be78-11e8-95e6-539cc3efdf41.png)

Other than that, this is seriously impressive work. I'm playing with it right now, see what I can come up with^^. Thank you !

**Comment by J-11** [comment]
> 
> 
> Is it OK with chrome?

同样的问题，firefox 62.0.3 (64 位)。chrome没问题。

**Comment by ytjchan** [comment]
Same here with Firefox 62.0.3 (64-bit)
(Edit) Turns out you can still obtain the exported image by going to _(Alt)->Tools->Page Info->Media_
<img width="452" alt="capture" src="https://user-images.githubusercontent.com/31836434/47556977-32506a80-d942-11e8-9acb-23ad34c7fd79.PNG">
(I love the tool, thanks!)

**Comment by starkgate** [comment]
Good to know. Still doesn't work for some large images though (firefox or chrome).
