### ISSUE TITLE
一喵要开店了吗？

### ISSUE THREAD

**Issue by yihuishou** [lllyasviel/MangaCraft#8]
![qq 20190119131406](https://user-images.githubusercontent.com/26241263/51422589-2ba55c80-1bec-11e9-92a4-cb97e7d50210.png)

MC 的颜色边界控制能力比S2P 要好很多~ 不知道有没有离线版可用呢？ QAQ

**Comment by Gyrosona** [comment]
yes, it's very strange! they went completely silent. I have no idea why.

**Comment by HynoR** [comment]
the server was closed,and our domain is under DNS cache pollution
